version: 2
jobs:
  build-be:
    working_directory: /src
    docker:
      - image: jwnwilson/noelwilson_2017
      - image: mongo:3.4.0
    steps:
      - checkout
      - restore_cache:
          key: v3-be-{{ checksum "server/requirements/common.txt" }}
          paths:
            - /src/server/venv
      - run:
          command: './ops/reset_db.sh;'
      - run:
          command: 'cd server; ./scripts/setup.sh'
      - save_cache:
          key: v3-be-{{ checksum "server/requirements/common.txt" }}
          paths:
            - /src/server/venv
      - run:
          command: 'cd server; ./scripts/pylint.sh; ./scripts/test.sh'
      - store_artifacts:
          path: ./server/.cov
          prefix: be-tests
  build-fe:
    working_directory: /src
    docker:
      - image: node:6.11.2
    steps:
      - checkout
      - restore_cache:
          key: v2-fe-{{ checksum "client/package.json" }}
          paths:
            - /src/client/node_modules
      - run:
          command: 'cd client; npm install'
      - save_cache:
          key: v2-fe-{{ checksum "client/package.json" }}
          paths:
            - /src/client/node_modules
      - run:
          command: 'cd client; ./node_modules/.bin/webpack'
      - save_cache:
          key: v1-fe-static-{{ .Revision }}
          paths:
            - /src/static
      - run:
          command: 'cd client; npm test'
      - store_artifacts:
          path: /src/client/test-results
          prefix: fe-tests
workflows:
  version: 2
  build:
    jobs:
      - build-fe
      - build-be
