version: '3'
services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./ops/Dockerfile_nginx
    image: docker.io/jwnwilson/noelwilson2018-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - media:/app/src/server/media

  server:
    restart: always
    container_name: noelwilson2018-server-prod
    build:
      context: .
      dockerfile: ./ops/Dockerfile_server
    image: docker.io/jwnwilson/noelwilson2018-server
    user: root
    working_dir: /app/src/server
    command: gunicorn webapp.wsgi:application -w 3 -b :8000 -t 120
    tty: true
    ports:
      - 8000
    volumes:
      - media:/app/src/server/media
      - site-packages:/usr/local/lib/python3.6/site-packages
    depends_on:
      - db
      - cache

  cache:
   image: memcached
   ports:
     - 11211:11211
   entrypoint:
    - memcached
    - -m 64

  db:
    build:
      context: .
      dockerfile: ./ops/Dockerfile_db
    image: docker.io/jwnwilson/noelwilson2018-db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data:z

volumes:
  db_data:
  media:
  site-packages:
