apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: “true”
    kubernetes.io/ingress.global-static-ip-name: noel-wilson-ip
spec:
  rules:
  - host: jwnwilson.com
    http:
      paths:
      - path: /
        backend:
          serviceName: server
          servicePort: 8000
  tls:
  - secretName: tls-staging-cert
    hosts:
      - jwnwilson.com