apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: server
      labels:
        name: api
    spec:
      containers:
        - name: server
          image: docker.io/jwnwilson/jwnwilson_server
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.05"
            limits:
              memory: "250Mi"
              cpu: "0.3"
          tty: true
          volumeMounts:
            - mountPath: /app/src/server/media
              name: media
          workingDir: /app/src/server
      restartPolicy: Always
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: api
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    name: server
status:
  loadBalancer: {}
