FROM python
MAINTAINER Noel Wilson <jwnwilson@gmail.com>

# Install dependancies as one layer
# Reinstalling pip as not working with pipenv
RUN apt-get update && \
  apt-get install -y libmemcached-dev zlib1g-dev && \
  curl https://bootstrap.pypa.io/get-pip.py | python

# Add project files to DIR
COPY ./ops/bashrc /root/.bashrc
COPY . /app

WORKDIR /app/src/server

ENV PIPENV_VENV_IN_PROJECT True

RUN python3 -m venv .venv && \
  pip3 install pipenv && \
  pipenv install --dev
