FROM python
MAINTAINER Noel Wilson <jwnwilson@gmail.com>

COPY ./ops/bashrc /root/.bashrc
COPY . /app

WORKDIR /app/src/server

# Pip is broken this fixes it
RUN curl https://bootstrap.pypa.io/get-pip.py | python && \
  pip3 install pipenv && \
  pipenv install --system --deploy
