FROM python
MAINTAINER Noel Wilson <jwnwilson@gmail.com>

RUN pip3 install pipenv

COPY ./ops/bashrc /root/.bashrc
ADD . /app

WORKDIR /app/src/server
RUN /bin/bash -c "source /app/src/server/setup.sh"
