# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderLink',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='link_1',
            new_name='cta_1',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='link_2',
            new_name='cta_2',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='link_3',
            new_name='cta_3',
        ),
        migrations.AddField(
            model_name='header',
            name='cta_url_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='cta_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='cta_url_3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
