# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cms', '0002_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='cms.Blog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entrytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_entrytag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.EntryTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
