# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 14:25
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import webapp.cms.models.modules.blog


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_blog_image_chooser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtail.embeds.blocks.EmbedBlock())]),
        ),
    ]
