# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_portfollio'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='component',
            field=models.CharField(default='HeroImage', max_length=255),
        ),
        migrations.AddField(
            model_name='portfollio',
            name='component',
            field=models.CharField(default='HeroImage', max_length=255),
        ),
    ]
