# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20181118_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.URLField(default=None),
        ),
    ]
