# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180520_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfollio',
            name='component',
            field=models.CharField(default='Portfollio', max_length=255),
        ),
    ]
