# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_blog_image_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('modulepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.ModulePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.modulepage',),
        ),
    ]
