# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180416_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Module')),
                ('test', models.CharField(max_length=255)),
            ],
            bases=('cms.module',),
        ),
    ]
