# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 08:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_entry_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], default=None),
            preserve_default=False,
        ),
    ]
