# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0006_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Nav Item',
                'verbose_name_plural': 'Nav Items',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='header',
        ),
        migrations.RemoveField(
            model_name='test',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'ordering': ['title'], 'verbose_name_plural': 'Headers'},
        ),
        migrations.RemoveField(
            model_name='header',
            name='cta_1',
        ),
        migrations.RemoveField(
            model_name='header',
            name='cta_2',
        ),
        migrations.RemoveField(
            model_name='header',
            name='cta_3',
        ),
        migrations.RemoveField(
            model_name='header',
            name='cta_url_1',
        ),
        migrations.RemoveField(
            model_name='header',
            name='cta_url_2',
        ),
        migrations.RemoveField(
            model_name='header',
            name='cta_url_3',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='cta',
            name='category',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='cms.Header'),
        ),
        migrations.AddField(
            model_name='cta',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
