# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-24 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20190224_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='listing_iamge',
            new_name='listing_image',
        ),
    ]
