# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0007_contactme'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfollioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Portfollio Item',
                'verbose_name_plural': 'Portfollio Items',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='portfollio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfollioitem',
            name='category',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfollio', to='cms.Portfollio'),
        ),
        migrations.AddField(
            model_name='portfollioitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='portfollioitem',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
