# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 08:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20180417_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta',
            name='category',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctas', to='cms.Header'),
        ),
    ]
