# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20181119_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='portfolio',
            new_name='entries',
        ),
    ]
