# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 22:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20180524_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfollioitem',
            name='category',
        ),
        migrations.AddField(
            model_name='portfollioitem',
            name='portfollio',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfollio_items', to='cms.Portfollio'),
        ),
    ]
