# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0009_auto_20180524_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.BaseModule')),
                ('component', models.CharField(default='Portfolio', max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('cms.basemodule', models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('portfolio', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='cms.Portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='portfollio',
            name='basemodule_ptr',
        ),
        migrations.RemoveField(
            model_name='portfollioitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfollioitem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portfollioitem',
            name='portfollio',
        ),
        migrations.DeleteModel(
            name='Portfollio',
        ),
        migrations.DeleteModel(
            name='PortfollioItem',
        ),
    ]
