# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20180525_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text',
        ),
        migrations.AddField(
            model_name='about',
            name='cv_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
