# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20180525_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepage',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.Footer'),
        ),
    ]
