# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_modulepage_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.ModulePage'),
        ),
    ]
