# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_footer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='component',
        ),
        migrations.RemoveField(
            model_name='contactme',
            name='component',
        ),
        migrations.RemoveField(
            model_name='heroimage',
            name='component',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='component',
        ),
    ]
