# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_wrapimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapimage',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
